### ISSUE TITLE
"chrM" not being excluded

### ISSUE THREAD

**Issue by kevbrick** [dejunlin/hicrep#15]
Hi, 

I get an error when I run hicrep on my mouse HiC mcool files (mm10 genome). Basically, the lack of data for chrM is causing hicrep to fail. I see that you have rule in the code to exclude chromosome "M", but not "chrM" (line 161 hicrep.py). Would it be possible to allow for more general nomenclature of the mitochondrial chromosome?  

Right now, I get around the issue by explicitly listing all chromosomes as an argument but would rather not need to do that.

**Error is shown below: Python script uses the toy example from github README with my own mcool files** 
```
>python hicrep_test.py 
Traceback (most recent call last):
  File "hicrep_test.py", line 30, in <module>
    scc = hicrepSCC(cool1, cool2, h, dBPMax, bDownSample)
  File "/home/kevbrick/data/get_sequencing_data/hicrep/lib/python3.8/site-packages/hicrep/hicrep.py", line 161, in hicrepSCC
    assert mS1.size > 0, "Contact matrix 1 of chromosome %s is empty" % (chrName)
AssertionError: Contact matrix 1 of chromosome chrM is empty
```

Thanks for the great tool !
Kevin

**Comment by dejunlin** [comment]
Thank you for looking into this issue! Unfortunately, I have projects that uses custom chromosome labels so that I can't afford excluding things like `chr*`. In general, I regretted doing such kind of implicit and silent exclusion of data but at some point I thought 'M' was common enough and most of real chromosome labels start with 'chr' so I did it anyway. Moreover, there isn't an agreement in the genomics community on chromosome label or mitochondria label so excluding any particular pattern that people don't necessarily agree on can silently generate unintended results.

A more reasonable alternative would be to add a command line option to exclude certain chromosome labels so that the users would know what data to exclude. I am currently preoccupied with other work so I don't have time to work on this right now but I can help with a PR if you can come up with one. Thanks!

**Comment by dejunlin** [comment]
On a higher level, I have never seen mitochondrial reads in hi-c used in any meaningful way so it's weird that most pipeline don't automatically exclude them, which causes all the downstream analysis to have to watch out for them, which is very unreasonable and costs the whole community more time to deal with it. The ultimate solution would be to ask the data processing pipeline to exclude such unwanted data -- why do people keep them if they don't use them anyway?
