### ISSUE TITLE
`AssertionError` when running hicrep

### ISSUE THREAD

**Issue by PanZiwei** [dejunlin/hicrep#18]
Hi,

Thank you so much for the great tool for python implementation. I would like to ask several questions if possible.

1.  I get an error `AssertionError: Contact matrix 1 of chromosome chrY is empty` when I run hicrep on my dataset of mouse HiC mcool/cool files with mm10. I checked the issues and found a similar issue in https://github.com/dejunlin/hicrep/issues/15.
Is the lack of data on chrY causing the AssertionError above? Is there a way to find the chromosome of missing data before running the package?

2. I am interested in generating a heatmap to assess the reproducibility of Hi-C replicates. Is there a way to achieve the goal with the hicrep.py? 

Thank you so much for your help!

Best,
Ziwei

**Comment by dejunlin** [comment]
Hi,

> I get an error AssertionError: Contact matrix 1 of chromosome chrY is empty when I run hicrep on my dataset of mouse HiC mcool/cool files with mm10. I checked the issues and found a similar issue in https://github.com/dejunlin/hicrep/issues/15. Is the lack of data on chrY causing the AssertionError above? Is there a way to find the chromosome of missing data before running the package?

Yes. This most likely is due to empty data in chrY. This implementation doesn't provide the functionality to automatically exclude missing data. You could just run the tool multiple times to titrate out the list of empty chromosomes by using the `--excludeChr` cmd option, which is a bit hacky but doable. Another possibility is to write your own script using our the Cooler API to screen for empty chromosomes.

> I am interested in generating a heatmap to assess the reproducibility of Hi-C replicates. Is there a way to achieve the goal with the hicrep.py?

This tools itself doesn't provide plotting functions. You can resort to other plotting software like matplotlib or seaborn for that.
