### ISSUE TITLE
About Interpretation of results

### ISSUE THREAD

**Issue by qianXX** [dejunlin/hicrep#5]
Hi！thanks for this work.

I have one problem.

When I get the output file outputSCC.txt which have a list of SCC scores for each chromosome, how can I explain this result?
Because the final result I want to get is **one reproducibility score for two samples**, not chromosome level.

**Comment by dejunlin** [comment]
Hi @qianXX , the original HiCRep paper didn't detail how to combine SCC scores from multiple chromosomes in order to achieve what you want. However, in practice, I have seen people using the median or mean of the the chromosome SCC scores as the representation of the sample SCC score. That said, I have not seen any scientific proof of the median or the mean being the best way of doing this so you might need to make your own decision based on your application. Hope this helps!

**Comment by qianXX** [comment]
Thanks, it works.
